### ISSUE TITLE
Task 'backend-clone' fails because of a missing repository

### ISSUE THREAD

**Issue by Metaa** [WatchBeam/developers#141]
When I try to build the stuff using ``npm run build``, the task ``backend-clone`` fails, because of restricted / missing repositories.
I already tried ``gulp recompile`` as suggested in the README.

```log
[06:07:26] 'backend-clone' errored after 4.13 s
[06:07:26] Error: Command failed: cd build/tmp && git clone -b master git@github.com:WatchBeam/backend.git
Cloning to 'backend' ...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
[06:07:26] 'pull-client-repos' errored after 4.26 s
[06:07:26] Error: Errorful response getting WatchBeam/beam-client-swift: Forbidden
    at fetch.then.response (/opt/beam/developers/build/docs.js:272:27)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Is there something I'm doing wrong or is it the setup that just doesn't work for externals?

**Comment by EthanWaite** [comment]
Hi! 👋 

Thanks for wanting to contribute! 😄 You should be able to run `gulp recompile` and then `npm start` to get started, and you don't need to run a full build at all. This is because running the build command pulls some docs from private repositories, but running `gulp recompile` will still produce a functioning site aside from the auto-generated "REST API" page.

Were you having any problems running gulp recompile?

**Comment by Metaa** [comment]
Hi Ethan,

no, I'm not at all having problems with gulp here!
I had to run it after the initial failing ``npm run build`` to get the HTML files and then just using ``npm start`` seems to work 😄

**Comment by SimonSchick** [comment]
Mhh, should probably add an error message for that scenario, it's a little bit obsure.
